parameters:
#    a_snet_g_cal.example.class: ASnet\GCalBundle\Example

services:
#    a_snet_g_cal.example:
#        class: %a_snet_g_cal.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
